require "num"
require "json"

module CrySpace
  class StateSpace
    # Generates an interactive HTML dashboard containing a Step Response plot using Chart.js.
    def step_plot(filename : String, n_steps = 200)
      times, states, outputs = step_response(n_steps: n_steps)
      
      t_arr = times.to_a
      
      # Build datasets for each output channel
      datasets = Array(Hash(String, JSON::Any)).new
      p = n_outputs
      m = n_inputs
      
      # For each output, extract the simulation curve
      p.times do |out_idx|
        m.times do |in_idx|
          data_points = Array(Float64).new(t_arr.size)
          t_arr.size.times do |t_idx|
            # outputs is a list of 2D tensors of shape [p, m]
            data_points << outputs[t_idx][out_idx, in_idx].value
          end
          
          label = p > 1 || m > 1 ? "Output #{out_idx + 1} (Input #{in_idx + 1})" : "Step Response"
          
          ds = {
            "label" => JSON::Any.new(label),
            "data" => JSON::Any.new(data_points.map { |v| JSON::Any.new(v) }),
            "borderColor" => JSON::Any.new("#00bcd4"),
            "backgroundColor" => JSON::Any.new("rgba(0, 188, 212, 0.1)"),
            "borderWidth" => JSON::Any.new(2.0),
            "fill" => JSON::Any.new(true),
            "tension" => JSON::Any.new(0.1)
          }
          datasets << ds
        end
      end
      
      times_json = t_arr.map(&.round(4)).to_json
      datasets_json = datasets.to_json
      
      html = <<-HTML
      <!DOCTYPE html>
      <html>
      <head>
        <title>CrySpace - Step Response</title>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; background: #0f172a; color: #f8fafc; }
          .container { max-width: 900px; margin: 0 auto; background: #1e293b; padding: 30px; border-radius: 12px; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }
          h1 { color: #38bdf8; margin-bottom: 20px; font-weight: 400; text-align: center; }
          .footer { font-size: 12px; color: #64748b; text-align: center; margin-top: 20px; }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>System Step Response</h1>
          <canvas id="stepChart"></canvas>
          <div class="footer">Generated by CrySpace Control Systems Library</div>
        </div>
        <script>
          const ctx = document.getElementById('stepChart').getContext('2d');
          new Chart(ctx, {
            type: 'line',
            data: {
              labels: #{times_json},
              datasets: #{datasets_json}
            },
            options: {
              responsive: true,
              scales: {
                x: {
                  title: { display: true, text: 'Time (seconds)', color: '#94a3b8' },
                  grid: { color: '#334155' },
                  ticks: { color: '#94a3b8' }
                },
                y: {
                  title: { display: true, text: 'Amplitude', color: '#94a3b8' },
                  grid: { color: '#334155' },
                  ticks: { color: '#94a3b8' }
                }
              },
              plugins: {
                legend: { labels: { color: '#f8fafc' } }
              }
            }
          });
        </script>
      </body>
      </html>
      HTML
      
      File.write(filename, html)
    end
    
    # Generates an interactive HTML dashboard containing a Bode Plot (Magnitude & Phase) using Chart.js.
    def bode_plot(filename : String, omega : Float64Tensor? = nil)
      w_vec = omega || Float64Tensor.linear_space(-2.0, 3.0, 200).map { |v| 10.0 ** v }
      w_out, mag_db, phase_deg = bode_data(w_vec)
      w_arr = w_out.to_a
      
      # Formatting data for Chart.js logarithmic scale requires {x: freq, y: val} format
      mag_data = w_arr.map_with_index { |w, idx| {"x" => w.round(6), "y" => mag_db[idx].round(4)} }
      phase_data = w_arr.map_with_index { |w, idx| {"x" => w.round(6), "y" => phase_deg[idx].round(4)} }
      
      mag_json = mag_data.to_json
      phase_json = phase_data.to_json
      
      html = <<-HTML
      <!DOCTYPE html>
      <html>
      <head>
        <title>CrySpace - Bode Diagram</title>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; background: #0f172a; color: #f8fafc; }
          .container { max-width: 900px; margin: 0 auto; background: #1e293b; padding: 30px; border-radius: 12px; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }
          h1 { color: #38bdf8; margin-bottom: 25px; font-weight: 400; text-align: center; }
          .chart-box { margin-bottom: 30px; }
          .footer { font-size: 12px; color: #64748b; text-align: center; margin-top: 20px; }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>Bode Diagram</h1>
          
          <div class="chart-box">
            <canvas id="magChart"></canvas>
          </div>
          <div class="chart-box">
            <canvas id="phaseChart"></canvas>
          </div>
          
          <div class="footer">Generated by CrySpace Control Systems Library</div>
        </div>
        <script>
          const logScaleConfig = {
            type: 'logarithmic',
            position: 'bottom',
            title: { display: true, text: 'Frequency (rad/s)', color: '#94a3b8' },
            grid: { color: '#334155' },
            ticks: {
              color: '#94a3b8',
              callback: function(value, index, values) {
                // Return nice decade labels: 0.01, 0.1, 1, 10, 100
                const log10 = Math.log10(value);
                if (Math.abs(log10 - Math.round(log10)) < 1e-10) {
                  return value;
                }
                return null;
              }
            }
          };

          // Magnitude Chart
          new Chart(document.getElementById('magChart').getContext('2d'), {
            type: 'line',
            data: {
              datasets: [{
                label: 'Magnitude (dB)',
                data: #{mag_json},
                borderColor: '#10b981',
                backgroundColor: 'rgba(16, 185, 129, 0.1)',
                borderWidth: 2,
                fill: true,
                tension: 0.1,
                pointRadius: 0
              }]
            },
            options: {
              responsive: true,
              scales: {
                x: logScaleConfig,
                y: {
                  title: { display: true, text: 'Magnitude (dB)', color: '#94a3b8' },
                  grid: { color: '#334155' },
                  ticks: { color: '#94a3b8' }
                }
              },
              plugins: {
                legend: { labels: { color: '#f8fafc' } }
              }
            }
          });

          // Phase Chart
          new Chart(document.getElementById('phaseChart').getContext('2d'), {
            type: 'line',
            data: {
              datasets: [{
                label: 'Phase (deg)',
                data: #{phase_json},
                borderColor: '#fb7185',
                backgroundColor: 'rgba(251, 113, 133, 0.1)',
                borderWidth: 2,
                fill: true,
                tension: 0.1,
                pointRadius: 0
              }]
            },
            options: {
              responsive: true,
              scales: {
                x: logScaleConfig,
                y: {
                  title: { display: true, text: 'Phase (degrees)', color: '#94a3b8' },
                  grid: { color: '#334155' },
                  ticks: { color: '#94a3b8' }
                }
              },
              plugins: {
                legend: { labels: { color: '#f8fafc' } }
              }
            }
          });
        </script>
      </body>
      </html>
      HTML
      
      File.write(filename, html)
    end
  end

  class TransferFunction
    # Generates a Step Response plot from the transfer function.
    def step_plot(filename : String, n_steps = 200)
      to_statespace.step_plot(filename, n_steps)
    end
    
    # Generates a Bode Plot from the transfer function.
    def bode_plot(filename : String, omega : Float64Tensor? = nil)
      to_statespace.bode_plot(filename, omega)
    end
  end
end
